version: "3"
services:
  node-app:
    depends_on:
      - mongo-db
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env

  mongo-db:
    image: mongo
    env_file:
      - .env
    volumes:
      - mongo-db:/data/db

  redis-db:
    image: redis

volumes:
  mongo-db:
