version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env

  mongo-db:
    image: mongo
    env_file:
      - .db.env
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db:
