version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./ngnix/default.config:/etc/ngnix/conf.d/defaulte.conf:ro

  node-app:
    depends_on:
      - mongo-db
    build: .
    env_file:
      - .env

  mongo-db:
    image: mongo
    env_file:
      - .env
    volumes:
      - mongo-db:/data/db

  redis-db:
    image: redis

volumes:
  mongo-db:
